remote_theme: just-the-docs/just-the-docs
title: Batch-GPT Documentation
description: Documentation for the Batch-GPT service

# Theme settings
color_scheme: dark
search_enabled: true
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "Batch-GPT on GitHub":
    - "//github.com/tanmay17061/batch-gpt"

# Makes Aux links open in a new tab
aux_links_new_tab: true

# Navigation Structure
nav_external_links:
  - title: Batch-GPT on GitHub
    url: https://github.com/tanmay17061/batch-gpt
    hide_icon: false

# Enable copy code button
enable_copy_code_button: true

# Footer content
footer_content: "Copyright &copy; 2024 Batch-GPT. Distributed under the <a href=\"https://github.com/tanmay17061/batch-gpt/blob/main/LICENSE\">Apache License 2.0.</a>"

# Collections for organizing documentation
collections:
  docs:
    permalink: "/:collection/:path/"
    output: true