name: Release

on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        include:
          - binary: batch-gpt
            main_path: server/main.go
          - binary: batch-monitor 
            main_path: cmd/monitor/main.go
        exclude:
          - goarch: arm64
            goos: windows
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      
      - name: Display working directory and files
        run: |
          pwd
          ls -la
          
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          binary_name: ${{ matrix.binary }}
          project_path: "."  # Set the project root directory
          main: ${{ matrix.main_path }}
          ldflags: "-s -w"
          extra_files: LICENSE README.md
          pre_command: go mod tidy