name: Release

on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        include:
          - binary: batch-gpt
            main_path: ./server/main.go
          - binary: batch-monitor 
            main_path: ./cmd/monitor/main.go
        exclude:
          - goarch: arm64
            goos: windows
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          binary_name: ${{ matrix.binary }}
          main: ${{ matrix.main_path }}
          ldflags: "-s -w"
          extra_files: LICENSE README.md