name: Release

on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Same targets as before
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        include:
          - binary: batch-gpt
            path: server
          - binary: batch-monitor
            path: cmd/monitor
        exclude:
          - goarch: arm64
            goos: windows
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1
        with:
          project_path: ${{ matrix.path }}
          binary_name: ${{ matrix.binary }}
          github_token: ${{ secrets.TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}