name: Release

on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        binary: [batch-gpt, batch-monitor]
        include:
          - binary: batch-gpt
            path: server/main.go
          - binary: batch-monitor
            path: cmd/monitor/main.go
        exclude:
          - goarch: arm64
            goos: windows
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          binary_name: ${{ matrix.binary }}
          project_path: "./"
          build_flags: "-o ${{ matrix.binary }}"
          ldflags: "-s -w"
          extra_files: LICENSE README.md
